FROM public.ecr.aws/lambda/python:3.9

COPY clean.py ${LAMBDA_TASK_ROOT}/clean.py

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt -t ${LAMBDA_TASK_ROOT}

CMD ["clean.lambda_handler"]
