# Use Amazon's official Python runtime for Lambda as the base image
FROM public.ecr.aws/lambda/python:3.9

# Copy the Lambda function code into the container
COPY clean.py ${LAMBDA_TASK_ROOT}/clean.py

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt -t ${LAMBDA_TASK_ROOT}

# Set the Lambda function handler (filename.function_name)
CMD ["clean.lambda_handler"]
